# ─────────────────────
# General Configuration
# ─────────────────────
# Whether to send anonymous metrics using bstats.
Track-Metrics: true

# ──────────────────────
# Database Configuration
# ──────────────────────
Database-Details:
  Address: ""
  Database: ""
  Port: "3306"
  Username: "test"
  Password: "password"